name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          CI=false npm install --force

      - name: Build project
        run: |
          CI=false npm run build

      - name: Write SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Deploy with rsync
        run: |
          rsync -rltDzv --no-group --no-perms -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" build/ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/www/html/azure/pteadmin/

      - name: Remote post-deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/azure/pteadmin/
            echo "Deployment done ✅"
